apiVersion: v1
kind: Service
metadata:
   name: nginx-deploy-service
spec:
  type: LoadBalancer
  selector: 
      env: dev
  ports:
  - name: nginx-deploy-service-port
    protocol: TCP
    port: 80
    targetPort: 8080