apiVersion: v1
kind: Service
metadata:
   name: utc-service
spec:
  type: LoadBalancer
  selector: 
      app: nginx
  ports:
  - name: utc-service-port
    protocol: TCP
    port: 80
    targetPort: 8080