apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: dev
  name:  utc-app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: 376129840399.dkr.ecr.us-east-1.amazonaws.com/jenkins-ci:v1.24
        resources:
          limits:
            memory: "250Mi"
            # cpu: "400m"
          requests:
            memory: "150Mi"
            # cpu: "400m"
