apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
  type: LoadBalancer
